const APPROVERS_SELECTION = 'APP_SL';
const SIGNATORIES_SELECTION = 'SIG_SL';

const PICK_USER_TYPE_SIMPLE = 'PICK_USER_TYPE_SIMPLE';

export { APPROVERS_SELECTION, SIGNATORIES_SELECTION, PICK_USER_TYPE_SIMPLE };
